session AutoCorrode = HOL +
  sessions
    "HOL-Eisbach"
    "HOL-Library"
    "Word_Lib"
    (* AutoCorrode specific *)
    "Autogen"
    "Byte_Level_Encoding"
    "Crush"
    "Data_Structures"
    "Enum_Theory"
    "iq"
    "Micro_Rust_Examples"
    "Micro_Rust_Interfaces"
    "Micro_Rust_Interfaces_Core"
    "Micro_Rust_Parsing_Frontend"
    "Micro_Rust_Runtime"
    "Micro_Rust_Std_Lib"
    "Misc"
    "Lenses_And_Other_Optics"
    "Separation_Lenses"
    "Shallow_Micro_Rust"
    "Shallow_Separation_Logic"
  theories [document = false]
    "AutoCorrode"
